version: '3.7'

services:
  web:
    image: sanketkalode/bookapi
    ports:
     - 5000:5000
    networks:
      - application_network

    environment:
      MONGODB_DATABASE: BooksDB
      MONGODB_HOSTNAME: 172.31.82.194
      MONGODB_PORT: 27017
      FLASK_ENV: production

  server:
    image: sanketkalode/web-server:ubuntu
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - application_network
    depends_on:
      - web

networks:
  application_network:
    driver: bridge